/home/www/ulysses/webclient/scripts/connection/connection.js File Reference
Functions
function CONNECTION_ConnectJabber (XML)
function CONNECTION_SendJabber ()
function CONNECTION_ReceiveConnection ()
function CONNECTION_ReceiveXml ()
Function Documentation
function CONNECTION_ConnectJabber (XML)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Jabber Connection This file has all functions that is used to provide a connection with a Jabber Server Start connection to Jabber server
Returns: none
References CONNECTION_SendJabber(), LOGIN_Interface(), MainData, MESSAGE_GetProfile(), MESSAGE_Presence(), MESSAGE_SendPasswd(), MESSAGE_SendUsername(), MESSAGE_StartConnection(), MESSAGE_UserList(), and MESSAGE_UserListInfo().
Referenced by CONNECTION_ReceiveConnection(), LOGIN_Load4(), and LOGIN_Login().
function CONNECTION_ReceiveConnection ()
Receive Connection messages and make all steps to connect user
Returns: none
References CONNECTION_ConnectJabber(), CONNECTION_SendJabber(), LOGIN_Load(), LOGIN_LoginFailed(), MainData, MESSAGE_Wait(), and PARSER_ParseXml().
Referenced by CONNECTION_SendJabber().
function CONNECTION_ReceiveXml ()
Receive a Jabber message when user is already connected
Returns: none
References CONNECTION_SendJabber(), MainData, MESSAGE_Wait(), PARSER_ParseXml(), and UTILS_GetText().
Referenced by CONNECTION_SendJabber().
function CONNECTION_SendJabber ()
Send a XML post
Returns: none
References CONNECTION_ReceiveConnection(), CONNECTION_ReceiveXml(), MainData, and MESSAGE_MakeXMPP().
Referenced by ADMIN_BanUser(), ADMIN_KickUser(), ADMIN_UnbanUser(), CHAT_SendMessage(), CONNECTION_ConnectJabber(), CONNECTION_ReceiveConnection(), CONNECTION_ReceiveXml(), CONTACT_ChangeStatus(), CONTACT_InviteUser(), CONTACT_ReceiveSubscribe(), CONTACT_RemoveUser(), GAME_AcceptChallenge(), GAME_DeclineChallenge(), GAME_HandleAdjourn(), GAME_HandleCancel(), GAME_HandleDraw(), GAME_SendAdjourn(), GAME_SendCancel(), GAME_SendChallenge(), GAME_SendDraw(), GAME_SendMove(), GAME_SendResign(), GAME_StartObserverGame(), INTERFACE_AddOldGameResult(), INTERFACE_SetNextButton(), INTERFACE_SetPrevButton(), INTERFACE_SetSearchButton(), INTERFACE_ShowCreateRoomWindow(), INTERFACE_ShowGameRoomList(), LOGIN_Logout(), OLDGAME_OpenOldGameWindow(), PROFILE_SaveMyProfile(), PROFILE_StartProfile(), ROOM_EnterRoom(), ROOM_EnterRoomGame(), ROOM_ExitRoom(), ROOM_SendMessage(), ROOM_ShowGameRoomList(), and ROOM_ShowRoomList().