/home/www/ulysses/webclient/scripts/contact/contact.js File Reference
Functions
function CONTACT_StartContact ()
Show contact and contact online Div.
function CONTACT_HandleOnlinePresence (XML)
Handle presence to online list.
function CONTACT_AddUserOnlineList (User, Status)
Add user in the online list.
function CONTACT_OnlineSortUserByNick ()
Sort online list by nick name.
function CONTACT_OnlineSortUserByRating (Category)
Sort online list by rating category.
function CONTACT_HandleUserList (XML)
Handle user contact list.
function CONTACT_HandleUserPresence (XML)
Handle a user presence.
function CONTACT_InsertUser (User, Status, Subs, Group)
Add user in contact list.
function CONTACT_ShowUserMenu (Obj, Username)
Show user menu options.
function CONTACT_LoadUserContactList ()
Load contact list in interface.
function CONTACT_SortUsersByNick ()
Sort user contact list by nick name.
function CONTACT_SortUsersByRating (Category)
Sort user contact list by rating category.
Function Documentation
function CONTACT_AddUserOnlineList (User, Status)
Add user in the online list.
Add a user with status in online list.
Parameters:
User Username
Status User's status
Author: Rubens Suguimoto
References MainData.
function CONTACT_HandleOnlinePresence (XML)
Handle presence to online list.
Handle all presence from online list (General room);
Parameters:
XML The xml come from server with tag presence
Author: Ulysses Bonfim
References MainData.
Referenced by PARSER_ParsePresence().
function CONTACT_HandleUserList (XML)
Handle user contact list.
Handle user list received from jabber with yours contacts.
Returns: string
Author: Ulysses Bonfim
References CONTACT_InsertUser(), MainData, MESSAGE_InviteAccept(), and UTILS_GetNodeText().
Referenced by PARSER_ParseIq().
function CONTACT_HandleUserPresence (XML)
Handle a user presence.
Handle user presence for accept or decline invite to contact list and user status.
Returns: string
Author: Ulysses Bonfim
References CONTACT_ReceiveSubscribe(), CONTACT_ReceiveSubscribed(), CONTACT_ReceiveUnsubscribed(), CONTACT_SetUserStatus(), and UTILS_GetNodeText().
Referenced by PARSER_ParsePresence().
function CONTACT_InsertUser (User, Status, Subs, Group)
Add user in contact list.
Add user in MainData contact list, sort and show this user in interface.
Parameters:
User User's name
Status User's status
Subs User's subscribe status
Group User's group in contact list
Author: Pedro Rocha
References MainData.
Referenced by CONTACT_HandleUserList(), CONTACT_ReceiveSubscribe(), and CONTACT_ReceiveSubscribed().
function CONTACT_LoadUserContactList ()
Load contact list in interface.
Load user contact list in interface.
Author: Rubens Suguimoto
References MainData.
Referenced by LOGIN_Interface().
function CONTACT_OnlineSortUserByNick ()
Sort online list by nick name.
Sort on line user list by nick name. Sort in MainData and for each user in MainData online user, remove and insert it.
Author: Rubens Suguimoto
References MainData.
Referenced by ContactOnlineObj().
function CONTACT_OnlineSortUserByRating (Category)
Sort online list by rating category.
Sort on line user list by rating. Sort in MainData and for each user in MainData online user, remove and insert it.
Parameters:
Category Chess game category
Author: Rubens Suguimoto
References MainData.
Referenced by ContactOnlineObj().
function CONTACT_ShowUserMenu (Obj, Username)
Show user menu options.
Show user menu to send private message, match, view profile, etc.
Parameters:
Obj Object with menu options and functions
Username User's name
Author: Pedro Rocha
Setting options
References CHAT_OpenChat(), CONTACT_InviteUser(), CONTACT_RemoveUser(), INTERFACE_HideUserMenu(), INTERFACE_ShowUserMenu(), MainData, PROFILE_StartProfile(), UTILS_AddListener(), UTILS_GetText(), UTILS_RemoveListener(), WINDOW_BanUser(), WINDOW_Challenge(), WINDOW_Confirm(), and WINDOW_KickUser().
Referenced by INTERFACE_CreateUser(), and INTERFACE_CreateUserElement().
function CONTACT_SortUsersByNick ()
Sort user contact list by nick name.
Sort user online list by nick name. Sort in MainData and for each user in MainData online user, remove and insert it.
Author: Rubens Suguimoto and Danilo Yorinori
References MainData.
Referenced by ContactObj().
function CONTACT_SortUsersByRating (Category)
Sort user contact list by rating category.
Sort user contact list by rating. Sort in MainData and for each user in MainData online user, remove and insert it.
Parameters:
Category Chess game category
Author: Rubens Suguimoto and Danilo Yorinori
References MainData.
Referenced by ContactObj().
function CONTACT_StartContact ()
Show contact and contact online Div.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Handle contacts and user status Create contact list object and contact online list object. Hide contact list and show online list.
Author: Rubens Suguimoto
References ContactObj(), ContactOnlineObj(), and MainData.
Referenced by LOGIN_Interface().