/home/www/ulysses/webclient/scripts/game/challenge.js File Reference
Functions
function GAME_HandleChallenge (XML)
function GAME_HandleOffer (XML)
function GAME_HandleAccept (XML)
function GAME_HandleDecline (XML)
function GAME_ChallengeError (XML)
function GAME_SendChallenge (Oponent, Color, Time, Inc, Category, Rated, GameID)
function GAME_AcceptChallenge (MatchID)
function GAME_DeclineChallenge (MatchID)
Function Documentation
function GAME_AcceptChallenge (MatchID)
Accept the challenge with the specified MatchID
Parameters:
MatchID Id of the match to be accepted
Returns: void
Author: Pedro
References CONNECTION_SendJabber(), and MESSAGE_ChallengeAccept().
Referenced by INTERFACE_ShowChallengeWindow().
function GAME_ChallengeError (XML)
Handle errors on challenge
Referenced by GAME_HandleOffer().
function GAME_DeclineChallenge (MatchID)
Decline the challenge with the specified MatchID
Parameters:
MatchID Id of the match to be declined
Returns: void
Author: Pedro
References CONNECTION_SendJabber(), and MESSAGE_ChallengeDecline().
Referenced by INTERFACE_ShowChallengeWindow(), and WINDOW_Challenge().
function GAME_HandleAccept (XML)
Handle Accept
References MainData, and MESSAGE_ChangeStatus().
Referenced by GAME_HandleChallenge().
function GAME_HandleChallenge (XML)
3C CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Handle Challenge
References GAME_HandleAccept(), GAME_HandleDecline(), and GAME_HandleOffer().
Referenced by PARSER_ParseIq().
function GAME_HandleDecline (XML)
Handle Decline
References MainData, WINDOW_RemoveWindow(), and WindowObj().
Referenced by GAME_HandleChallenge().
function GAME_HandleOffer (XML)
Handle Offer
References GAME_ChallengeError(), MainData, and WINDOW_Challenge().
Referenced by GAME_HandleChallenge().
function GAME_SendChallenge (Oponent, Color, Time, Inc, Category, Rated, GameID)
Send a challenge message to 'Username'
References CONNECTION_SendJabber(), MainData, and MESSAGE_Challenge().
Referenced by INTERFACE_ShowChallengeWindow().