/home/www/ulysses/webclient/scripts/interface/game.js File Reference
Functions
function INTERFACE_GameBoardObj (GameID, Player1, Player2, YourColor, PieceSize)
function INTERFACE_CreateGame ()
function INTERFACE_ShowGame (Div)
function INTERFACE_HideGame ()
function INTERFACE_FinishGame ()
function INTERFACE_RemoveGame ()
function INTERFACE_ObserverMode ()
function INTERFACE_OldGameMode ()
function INTERFACE_ClearBoard ()
function INTERFACE_SetBoard (BoardArray)
function INTERFACE_InsertPiece (Piece, Line, Col)
function INTERFACE_RemovePiece (Line, Col)
function INTERFACE_UpdateBoard (OldBoard, NewBoard)
function INTERFACE_UndoMove ()
function INTERFACE_SetTurn (Color)
function INTERFACE_DecreaseTime ()
function INTERFACE_StartTimer ()
function INTERFACE_StopTimer ()
function INTERFACE_UpdateWTime (NewTime)
function INTERFACE_UpdateBTime (NewTime)
function INTERFACE_SetWTime ()
function INTERFACE_SetBTime ()
function INTERFACE_SetWPhoto (Img)
function INTERFACE_SetBPhoto (Img)
function INTERFACE_AddMove (NumTurn, Move, ShortMove, WTime, BTime)
function INTERFACE_RemoveMove ()
function INTERFACE_CreateBoard (MyColor, PieceSize)
function INTERFACE_CreateTimer ()
function INTERFACE_CreateGameOptions (GameID)
function INTERFACE_CreateMoveList ()
function INTERFACE_CreatePhoto (WhitePlayer, BlackPlayer)
function INTERFACE_CreateTab (Div1, Div2)
function INTERFACE_CreateVerticalIndex (Color, Size)
function INTERFACE_CreateHorizontalIndex (Color, Size)
function INTERFACE_NewPiece (Piece, PlayerColor, Size)
function INTERFACE_CreateOldGameMoveList ()
function INTERFACE_CreateOldGameTab (DivMoves)
function INTERFACE_LastMove (Move)
function INTERFACE_FindBlock (id)
Function Documentation
function INTERFACE_AddMove (NumTurn, Move, ShortMove, WTime, BTime)
Show a new move in Move List
Parameters:
NumTurn is the turn number
Move is the move done
WTime is white time when move is done
BTime is black time when move is done
Returns: void
Author: Rubens and Pedro
References MainData, OLDGAME_GotoBoard(), UTILS_AddListener(), and UTILS_CreateElement().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_ClearBoard ()
Clean all pieces of a board
Parameters:
void
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_CreateBoard (MyColor, PieceSize)
Create a board
Parameters:
MyColor is player color in the game
PieceSize is the board piece size
Returns: board html div
Author: Rubens and Pedro
References UTILS_CreateElement(), and UTILS_HorizontalIndex().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateGame ()
Creating game div and set all attributes
Parameters:
void
Returns: void
Author: Rubens and Pedro
References GAME_RemoveGame(), INTERFACE_CreateBoard(), INTERFACE_CreateGameOptions(), INTERFACE_CreateHorizontalIndex(), INTERFACE_CreateMoveList(), INTERFACE_CreatePhoto(), INTERFACE_CreateTab(), INTERFACE_CreateTimer(), INTERFACE_CreateVerticalIndex(), and UTILS_CreateElement().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_CreateGameOptions (GameID)
Create game options
Parameters:
GameId is game id string
Returns: Options html div and Array of html elements
Author: Rubens and Pedro
References GAME_SendAdjourn(), GAME_SendCancel(), GAME_SendDraw(), GAME_SendResign(), UTILS_AddListener(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateHorizontalIndex (Color, Size)
Create horizontal indexes of board
Parameters:
Color is the board color
Size is size of blocks of each block in board
Returns: Horizontal index html list
Author: Rubens and Pedro
References UTILS_CreateElement(), and UTILS_HorizontalIndex().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateMoveList ()
Create a move list
Parameters:
void
Returns: MoveListDiv html div and MoveList html list
Author: Rubens and Pedro
References UTILS_CreateElement().
Referenced by INTERFACE_CreateGame(), and INTERFACE_ObserverMode().
function INTERFACE_CreateOldGameMoveList ()
Create OldGame move list with buttons to review all game moves
Parameters:
void
Returns: MoveListDiv html div and MoveList html list
Author: Rubens and Pedro
References OLDGAME_FirstBoard(), OLDGAME_LastBoard(), OLDGAME_NextBoard(), OLDGAME_PrevBoard(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_OldGameMode().
function INTERFACE_CreateOldGameTab (DivMoves)
Create tab with 1 div(this should be used in Observer and OldGame mode)
Parameters:
Div1 is first div in tab
Returns: Tab html Div
Author: Rubens and Pedro
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_ObserverMode(), and INTERFACE_OldGameMode().
function INTERFACE_CreatePhoto (WhitePlayer, BlackPlayer)
Create photo images and names
Parameters:
WhitePlayer is White player name
BlackPlayer is Black player name
Returns: Photo html div, WPhoto html img, BPhoto html img, WName html span and BName html span
Author: Rubens and Pedro
References UTILS_CreateElement(), and UTILS_ShortString().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateTab (Div1, Div2)
Create tabs with 2 divs
Parameters:
Div1 is first div in tab
Div2 is second div in tab
Returns: Tab html Div
Author: Rubens and Pedro
References UTILS_AddListener(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateTimer ()
Create timer elements
Parameters:
void
Returns: Timer html div, White Timer html span and Black Timer html span
Author: Rubens and Pedro
References UTILS_CreateElement().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateVerticalIndex (Color, Size)
Create vertical indexes of board
Parameters:
Color is the board color
Size is size of blocks of each block in board
Returns: Vertical index html list
Author: Rubens and Pedro
References UTILS_CreateElement().
Referenced by INTERFACE_CreateGame().
function INTERFACE_DecreaseTime ()
Decrease user time. Executed each second
Parameters:
void
Returns: void
Author: Rubens and Pedro
References MainData.
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_FindBlock (id)
Find a block with parameter Identificator
Parameters:
id is the block identificator
Returns: null ou Block HTML div element
Author: Rubens
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_FinishGame ()
Disable options and drag pieces
Parameters:
void
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_GameBoardObj (GameID, Player1, Player2, YourColor, PieceSize)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Interface functions that control game
References INTERFACE_AddMove(), INTERFACE_ClearBoard(), INTERFACE_CreateGame(), INTERFACE_DecreaseTime(), INTERFACE_FindBlock(), INTERFACE_FinishGame(), INTERFACE_HideGame(), INTERFACE_InsertPiece(), INTERFACE_LastMove(), INTERFACE_ObserverMode(), INTERFACE_OldGameMode(), INTERFACE_RemoveGame(), INTERFACE_RemoveMove(), INTERFACE_RemovePiece(), INTERFACE_SetBoard(), INTERFACE_SetBPhoto(), INTERFACE_SetBTime(), INTERFACE_SetTurn(), INTERFACE_SetWPhoto(), INTERFACE_SetWTime(), INTERFACE_ShowGame(), INTERFACE_StartTimer(), INTERFACE_StopTimer(), INTERFACE_UndoMove(), INTERFACE_UpdateBoard(), INTERFACE_UpdateBTime(), INTERFACE_UpdateWTime(), and MainData.
Referenced by GAME_StartGame(), GAME_StartObserverGame(), and OLDGAME_StartOldGame().
function INTERFACE_HideGame ()
Hide this game in the interface
Parameters:
void
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_InsertPiece (Piece, Line, Col)
Display a piece in specified Line and Col of the board
Parameters:
Piece is piece char
Line is line where is the piece will be place
Col is column where is the piece will be place
Returns: void
Author: Rubens and Pedro
References INTERFACE_NewPiece(), and UTILS_HorizontalIndex().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_LastMove (Move)
Change board to last move done
Parameters:
Move string (i.e: a2a3)
Returns: void
Author: Rubens
References UTILS_HorizontalIndex().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_NewPiece (Piece, PlayerColor, Size)
Create a new piece, with drag listener in 'PLayerColor' pieces
Parameters:
Piece is piece char
PlayerColor is the current player color
Size is size of blocks of each block in board
Returns: Piece html img
Author: Rubens and Pedro
References MainData, UTILS_CreateElement(), UTILS_GetText(), and UTILS_StartDragPiece().
Referenced by INTERFACE_InsertPiece().
function INTERFACE_ObserverMode ()
References INTERFACE_CreateMoveList(), and INTERFACE_CreateOldGameTab().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_OldGameMode ()
References INTERFACE_CreateOldGameMoveList(), and INTERFACE_CreateOldGameTab().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_RemoveGame ()
Remove this game
Parameters:
void
Returns: void
Author: Rubens and Pedro
References MainData, UTILS_GetText(), and WINDOW_Alert().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_RemoveMove ()
Remove last move in Move List (this is should be used when players agree to return one move)
Parameters:
void
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_RemovePiece (Line, Col)
Remove a piece from the board
Parameters:
Line is line where the piece was placed
Col is column where the piece was placed
Returns: void
Author: Rubens and Pedro
References UTILS_HorizontalIndex().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetBoard (BoardArray)
Clean the board and show 'BoardArray' in the screen
Parameters:
BoardArray is board in array of array format
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetBPhoto (Img)
Show black avatar image (in base64)
Parameters:
PhotoType is the image type (png/gif)
PhotoStr is the image in base64 format string
Returns: void
Author: Rubens and Pedro
References IMAGE_ImageDecode().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetBTime ()
Show black timer on interface
Parameters:
void
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetTurn (Color)
Show turn info to user
Parameters:
Color is the player color
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetWPhoto (Img)
Show white avatar image (in base64)
Parameters:
PhotoType is the image type (png/gif)
PhotoStr is the image in base64 format string
Returns: void
Author: Rubens and Pedro
References IMAGE_ImageDecode().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetWTime ()
Show white timer on interface
Parameters:
void
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_ShowGame (Div)
Show this game in the interface
Parameters:
void
Returns: true if game is showed with sucess, else false
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_StartTimer ()
Start timer
Parameters:
void
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_StopTimer ()
Stop timer
Parameters:
void
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_UndoMove ()
Undo the last move done by the user
Parameters:
void
Returns: void
Author: Rubens and Pedro
References MainData.
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_UpdateBoard (OldBoard, NewBoard)
Update the board on the screen, where the pieces is diferrent
Parameters:
OldBoard is current Board
NewBoard is new board that will be show
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_UpdateBTime (NewTime)
Update black timer
Parameters:
NewTime is the new time to be update
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_UpdateWTime (NewTime)
Update white timer
Parameters:
NewTime is the new time to be update
Returns: void
Author: Rubens and Pedro
Referenced by INTERFACE_GameBoardObj().