/home/www/ulysses/webclient/scripts/interface/chat.js File Reference
Functions
function INTERFACE_ShowChatMessage (Username, Message, YourMessage)
function INTERFACE_OpenChat (Username, Status)
function INTERFACE_ShowChat (Item, Hide)
function INTERFACE_HideChat (Item, Hide)
function INTERFACE_CloseChat (Username)
function INTERFACE_FocusChat (Username)
function INTERFACE_UnfocusChat (Username)
function INTERFACE_ChatListPositioning ()
function INTERFACE_CreateChat (Username, Status)
function INTERFACE_CreateChatList ()
Function Documentation
function INTERFACE_ChatListPositioning ()
Positioning chat list
Referenced by INTERFACE_CreateChatList().
function INTERFACE_CloseChat (Username)
Close a chat
Referenced by CHAT_CloseChat().
function INTERFACE_CreateChat (Username, Status)
Create chat elements
References CHAT_ChangeChatState(), CHAT_CloseChat(), CHAT_SendMessage(), INTERFACE_ShowChat(), UTILS_CreateElement(), and UTILS_ReturnKeyCode().
Referenced by INTERFACE_OpenChat().
function INTERFACE_CreateChatList ()
Create chat list elements
References INTERFACE_ChatListPositioning(), and UTILS_CreateElement().
Referenced by INTERFACE_CreateInterface().
function INTERFACE_FocusChat (Username)
Giving focus to a chat window
Referenced by CHAT_ReceiveMessage().
function INTERFACE_HideChat (Item, Hide)
Hide chat window
Referenced by CHAT_ChangeChatState().
function INTERFACE_OpenChat (Username, Status)
Create chat elements
References INTERFACE_CreateChat().
Referenced by CHAT_OpenChat().
function INTERFACE_ShowChat (Item, Hide)
Show chat window
Referenced by CHAT_ChangeChatState(), and INTERFACE_CreateChat().
function INTERFACE_ShowChatMessage (Username, Message, YourMessage)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Interface function for chat Show a message in a open chat
References MainData, UTILS_CreateElement(), and UTILS_GetTime().
Referenced by CHAT_ReceiveMessage(), and CHAT_SendMessage().
function INTERFACE_UnfocusChat (Username)
Remove focus of a chat window
Referenced by CHAT_ChangeChatState().