/home/www/ulysses/webclient/scripts/interface/room.js File Reference
Functions
function RoomObj (Roomname)
function INTERFACE_CreateRoom (RoomName)
function INTERFACE_ShowRoom ()
function INTERFACE_HideRoom ()
function INTERFACE_RemoveRoom ()
function INTERFACE_AddMsgInRoom (Username, Msg, Timestamp)
function INTERFACE_RefreshOccupantsNumber (RoomName)
function INTERFACE_ShowRoomList (Rooms)
function INTERFACE_HideRoomList ()
function INTERFACE_HideGameRoomList ()
function INTERFACE_ShowGameRoomList (GameId, GameName, P1, P2, GameType)
function INTERFACE_ChangeRoomListVisibility ()
function INTERFACE_RemoveRoomFromList (Room)
function INTERFACE_ShowEmoticonList (RName)
function INTERFACE_HideEmoticonList ()
function INTERFACE_FocusRoom (RoomName)
function INTERFACE_CreateRoomInBar (RoomName)
function INTERFACE_CloseRoom ()
function INTERFACE_CreateRooms ()
function INTERFACE_ShowCreateRoomWindow ()
function INTERFACE_ShowCancelRoomWindow ()
Function Documentation
function INTERFACE_AddMsgInRoom (Username, Msg, Timestamp)
Referenced by RoomObj().
function INTERFACE_ChangeRoomListVisibility ()
Show or hide list of user's rooms
References MainData, ROOM_FocusRoom(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_CreateRooms().
function INTERFACE_CloseRoom ()
Close the room that are displayed as a secondary room
Referenced by ROOM_RemoveRoom().
function INTERFACE_CreateRoom (RoomName) [private]
Create a room
Room name;
Returns: RoomDiv, User list and Message list in this room Pedro and Rubens
References INTERFACE_ShowEmoticonList(), ROOM_SendMessage(), UTILS_CreateElement(), and UTILS_ReturnKeyCode().
Referenced by RoomObj().
function INTERFACE_CreateRoomInBar (RoomName)
References MainData, ROOM_ExitRoom(), ROOM_FocusRoom(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by ROOM_CreateRoom(), and ROOM_RemoveRoom().
function INTERFACE_CreateRooms () [private]
Create rooms div
References INTERFACE_ChangeRoomListVisibility(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_CreateLeft().
function INTERFACE_FocusRoom (RoomName)
Give focus to a room in change room bar
References MainData, and ROOM_FocusRoom().
Referenced by ROOM_FocusRoom().
function INTERFACE_HideEmoticonList ()
Hide emoticon list
Referenced by INTERFACE_ShowEmoticonList().
function INTERFACE_HideGameRoomList ()
Hide game room list menu
Returns: bool
Author: Ulysses
Referenced by INTERFACE_ShowGameRoomMenu().
function INTERFACE_HideRoom ()
Referenced by RoomObj().
function INTERFACE_HideRoomList ()
Hide room list menu
void
Returns: void
Author: Pedro
Referenced by INTERFACE_ShowRoomMenu().
function INTERFACE_RefreshOccupantsNumber (RoomName)
References MainData.
Referenced by ROOM_HandleRoomPresence(), and ROOM_RemoveRoom().
function INTERFACE_RemoveRoom ()
Referenced by RoomObj().
function INTERFACE_RemoveRoomFromList (Room)
Remove a room from room list if RoomListMenu is opened
Parameters:
Room name that will be removed from list
Returns: void
Author: Rubens
Referenced by ROOM_RemoveRoom().
function INTERFACE_ShowCancelRoomWindow ()
Create elements to cancel room creation window and return divs and array of buttons
Returns: Div, Array
See also: WINDOW_CancelRoom();
Author: Danilo Kiyoshi Simizu Yorinori
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_CancelRoom().
function INTERFACE_ShowCreateRoomWindow ()
Create elements to create room window and return divs and array of buttons
@ return Div, Array @ see WINDOW_CreateRoom(); @ author Danilo Kiyoshi Simizu Yorinori
References CONNECTION_SendJabber(), MainData, MESSAGE_Presence(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_Alert().
Referenced by WINDOW_CreateRoom().
function INTERFACE_ShowEmoticonList (RName)
Show emoticon list
References INTERFACE_HideEmoticonList(), MainData, UTILS_AddListener(), UTILS_CreateElement(), and UTILS_RemoveListener().
Referenced by INTERFACE_CreateRoom().
function INTERFACE_ShowGameRoomList (GameId, GameName, P1, P2, GameType)
Show game room list in the room menu
Parameters:
Rooms An Array with game rooms
Returns: bool
Author: Ulysses
References CONNECTION_SendJabber(), GAME_StartGame(), GAME_StartObserverGame(), MainData, MESSAGE_Presence(), UTILS_Capitalize(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_Alert().
Referenced by ROOM_HandleGameRoomInfoList().
function INTERFACE_ShowRoom ()
Referenced by RoomObj().
function INTERFACE_ShowRoomList (Rooms)
Show room list in the room menu, if it exists
Array of room names
Returns: void
Author: Pedro
References ROOM_EnterRoom(), and UTILS_CreateElement().
Referenced by ROOM_HandleRoomList().
function RoomObj (Roomname)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Control rooms interface
References INTERFACE_AddMsgInRoom(), INTERFACE_CreateRoom(), INTERFACE_HideRoom(), INTERFACE_RemoveRoom(), INTERFACE_ShowRoom(), ROOM_SortUsersByNick(), ROOM_SortUsersByRating(), and UserListObj().
Referenced by DATA_AddRoom(), and ROOM_CreateRoom().