/home/www/ulysses/webclient/scripts/interface/window.js File Reference
Functions
function WindowObj (Height, Width, Div, Title, CloseCommands)
function WINDOW_ShowWindow (Element)
function WINDOW_CloseWindow ()
function WINDOW_SetId (Id)
function WINDOW_SetSize (Width, Height)
function WINDOW_SetTitle (Title)
function WINDOW_SetFocus ()
function WINDOW_SetBlur ()
function WINDOW_SetZIndex (Index)
function WINDOW_GetZIndex ()
function WINDOW_ConcatEventButtons (ButtonsList)
function WINDOW_CreateWindow (Height, Width, Div, Title)
function WINDOW_CreateAlert (Text)
function WINDOW_CreateConfirm (Text, Button1, Button2)
function WINDOW_CreateImageSend ()
Function Documentation
function WINDOW_CloseWindow ()
Referenced by WindowObj().
function WINDOW_ConcatEventButtons (ButtonsList)
Referenced by WindowObj().
function WINDOW_CreateAlert (Text)
Create elements of game alert window and returns div
Parameters:
Text Text to display in confirm box
Returns: Div; Array
See also: WINDOW_Alert();
Author: Danilo Kiyoshi Simizu Yorinori
References UTILS_CreateElement().
Referenced by WINDOW_Alert().
function WINDOW_CreateConfirm (Text, Button1, Button2)
Create elements of confirm request window and returns div
Parameters:
Text Text to display in confirm box
Button1 Value and Fuction of Button1
Button2 Value and Fuction of Button2
Returns: Div; Array
See also: WINDOW_Confirm();
Author: Danilo Kiyoshi Simizu Yorinori
References UTILS_AddListener(), and UTILS_CreateElement().
Referenced by WINDOW_Confirm().
function WINDOW_CreateImageSend ()
Create elements of send user image
Parameters:
Text Text to display in confirm box
Returns: Div; Array
See also: WINDOW_Confirm();
Author: Rubens and Fabiano
References IMAGE_CreateFormToEncode(), IMAGE_ImageEncode(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_ProfileImage().
function WINDOW_CreateWindow (Height, Width, Div, Title)
References UTILS_AddListener(), and UTILS_StartDragWindow().
Referenced by WindowObj().
function WINDOW_GetZIndex ()
Referenced by WindowObj().
function WINDOW_SetBlur ()
Referenced by WindowObj().
function WINDOW_SetFocus ()
Referenced by WindowObj().
function WINDOW_SetId (Id)
Referenced by WindowObj().
function WINDOW_SetSize (Width, Height)
Referenced by WindowObj().
function WINDOW_SetTitle (Title)
Referenced by WindowObj().
function WINDOW_SetZIndex (Index)
Referenced by WindowObj().
function WINDOW_ShowWindow (Element)
References MainData.
Referenced by WindowObj().
function WindowObj (Height, Width, Div, Title, CloseCommands)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Window Interface Object
References WINDOW_CloseWindow(), WINDOW_ConcatEventButtons(), WINDOW_CreateWindow(), WINDOW_GetZIndex(), WINDOW_SetBlur(), WINDOW_SetFocus(), WINDOW_SetId(), WINDOW_SetSize(), WINDOW_SetTitle(), WINDOW_SetZIndex(), and WINDOW_ShowWindow().
Referenced by DATA_AddChallengeWindow(), DATA_AddWindow(), DATA_ChangeWindowFocus(), DATA_FindWindow(), DATA_RemoveWindow(), GAME_HandleDecline(), WINDOW_Alert(), WINDOW_BanUser(), WINDOW_CancelRoom(), WINDOW_Challenge(), WINDOW_ChangeFocus(), WINDOW_Confirm(), WINDOW_CreateRoom(), WINDOW_Invite(), WINDOW_KickUser(), WINDOW_NewWindow(), WINDOW_OldGame(), WINDOW_OldGameSearch(), WINDOW_Profile(), WINDOW_ProfileConfirm(), WINDOW_ProfileImage(), WINDOW_RemoveWindow(), WINDOW_SearchUser(), WINDOW_SearchUserResult(), and WINDOW_UnbanUser().