/home/www/ulysses/webclient/scripts/login/load.js File Reference
Functions
function LOGIN_Load ()
function LOGIN_Load2 ()
function LOGIN_Load3 ()
function LOGIN_Load4 ()
function LOGIN_EndLoad ()
function LOGIN_LoadScripts ()
function LOGIN_LoadCss ()
function LOGIN_LoadImages ()
Function Documentation
function LOGIN_EndLoad ()
Remove load box from screen
References INTERFACE_EndLoad().
Referenced by LOGIN_Interface().
function LOGIN_Load ()
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Load images, scripts and css used in the interface from server Show load screen to user, and begin to load scripts
References INTERFACE_SetLoadPhrase(), INTERFACE_StartLoad(), LOGIN_EndLogin(), LOGIN_LoadCss(), and UTILS_GetText().
Referenced by CONNECTION_ReceiveConnection().
function LOGIN_Load2 ()
Start to load css files
References INTERFACE_SetLoadPhrase(), LOGIN_LoadScripts(), and UTILS_GetText().
Referenced by LOGIN_LoadCss().
function LOGIN_Load3 ()
Start to load images
References INTERFACE_SetLoadPhrase(), LOGIN_LoadImages(), and UTILS_GetText().
Referenced by LOGIN_LoadScripts().
function LOGIN_Load4 ()
Finish load process
References CONNECTION_ConnectJabber(), INTERFACE_SetLoadPhrase(), MainData, and UTILS_GetText().
Referenced by LOGIN_LoadImages().
function LOGIN_LoadCss ()
Load css files while interface is loading
References LOGIN_Load2(), and MainData.
Referenced by LOGIN_Load().
function LOGIN_LoadImages ()
Load images used in interface
References LOGIN_Load4(), and Preloader().
Referenced by LOGIN_Load3().
function LOGIN_LoadScripts ()
Load scripts files while interface is loading
References LOGIN_Load3(), and Preloader().
Referenced by LOGIN_Load2().