/home/www/ulysses/webclient/scripts/login/login.js File Reference
Functions
function LOGIN_Login (Username, Passwd, RememberPass)
function LOGIN_Logout ()
function LOGIN_Disconnected ()
function LOGIN_EndLogin ()
function LOGIN_Interface ()
function LOGIN_LoginFailed (Code)
Function Documentation
function LOGIN_Disconnected ()
Make logout
Returns: none
References INTERFACE_StopInterface(), and MainData.
Referenced by PARSER_ParseXml().
function LOGIN_EndLogin ()
Clear Login window and start interface
Returns: none
References INTERFACE_EndLogin().
Referenced by LOGIN_Load().
function LOGIN_Interface ()
Clear Login window and start interface
Returns: none
References CONTACT_LoadUserContactList(), CONTACT_StartContact(), INTERFACE_CreateInterface(), INTERFACE_ShowInterface(), and LOGIN_EndLoad().
Referenced by CONNECTION_ConnectJabber().
function LOGIN_Login (Username, Passwd, RememberPass)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Make login on Jabber Server
Returns: none
References CONNECTION_ConnectJabber(), MainData, UTILS_CreateCookie(), UTILS_DeleteCookie(), UTILS_GetText(), and UTILS_ValidateUsername().
Referenced by INTERFACE_StartLogin().
function LOGIN_LoginFailed (Code)
Show a error message on login
Returns: none
References MainData, and UTILS_GetText().
Referenced by CONNECTION_ReceiveConnection().
function LOGIN_Logout ()
Make logout
Returns: none
References CONNECTION_SendJabber(), INTERFACE_StopInterface(), MainData, MESSAGE_EndConnection(), and START_StartPage().
Referenced by INTERFACE_CreateTop().