/home/www/ulysses/webclient/scripts/parser/parser_presence.js File Reference
Functions
function PARSER_ParsePresence (XML)
Function Documentation
function PARSER_ParsePresence (XML)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Parse presence messages received from jabber
References CONTACT_HandleOnlinePresence(), CONTACT_HandleUserPresence(), and ROOM_HandleRoomPresence().
Referenced by PARSER_ParseXml().