/home/www/ulysses/webclient/scripts/utils/preloader.js File Reference
Functions
function Preloader (SrcArray, TypeNode, CallBack)
function LoadScript (Src)
function LoadImage (Src)
function Loaded ()
Function Documentation
function Loaded ()
References Preloader().
Referenced by Preloader().
function LoadImage (Src)
Referenced by Preloader().
function LoadScript (Src)
Referenced by Preloader().
function Preloader (SrcArray, TypeNode, CallBack)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Generic class to preload elements
References Loaded(), LoadImage(), and LoadScript().
Referenced by Loaded(), LOGIN_LoadImages(), and LOGIN_LoadScripts().