/home/www/ulysses/webclient/scripts/profile/profile.js File Reference
Functions
function PROFILE_HandleVCardProfile (XML)
function PROFILE_HandleInfoProfile (XML)
function PROFILE_HandleRatings (RatingNodes)
function PROFILE_StartProfile (Username)
function PROFILE_RemoveProfile (Username)
function PROFILE_SaveMyProfile ()
function PROFILE_CreateProfile ()
Function Documentation
function PROFILE_CreateProfile ()
Return a default message to create a basic profile
Returns: XMPP set profile message
Author: Pedro
References MainData, and MESSAGE_SetProfile().
Referenced by PARSER_ParseIqById().
function PROFILE_HandleInfoProfile (XML)
Handle info profile user
Parameters:
XML is the xml that contais profile informations
Returns: void
Author: Rubens
References MainData, and PROFILE_HandleRatings().
Referenced by PARSER_ParseIq().
function PROFILE_HandleRatings (RatingNodes)
Create an array with ratings and return it
Parameters:
RatingNodes Array of ratings with data
Returns: Array in format: each line is a rating type [1] lightning [2] blitz [3] Standard each column is a data [1] category [2] current rating [3] max rating [4] max rating date [5] number of games in category [6] number of wins [7] number of losses [8] numeber of draws
See also: CONTACT_HandleInfo(XML);
Author: Danilo Yorinori
References UTILS_ConvertTimeStamp().
Referenced by PROFILE_HandleInfoProfile().
function PROFILE_HandleVCardProfile (XML)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Handle Jabber vCard User
Parameters:
XML is the xml that contais vCard information
Returns: void
Author: Rubens
References INTERFACE_SetUserImage(), MainData, and UTILS_GetNodeText().
Referenced by PARSER_ParseIq().
function PROFILE_RemoveProfile (Username)
Remove Profile from data struct
Parameters:
Username is the jabber username
Returns: void
Author: Rubens
References MainData.
Referenced by WINDOW_Profile().
function PROFILE_SaveMyProfile ()
Save changes of profile
Parameters:
Username is the jabber username
Returns: void
Author: Rubens
References CONNECTION_SendJabber(), MainData, MESSAGE_GetProfile(), and MESSAGE_SetProfile().
Referenced by INTERFACE_ShowProfileWindow().
function PROFILE_StartProfile (Username)
Create profile in data Struct and show Profile window
Parameters:
Username is the jabber username
Returns: void
Author: Rubens
References CONNECTION_SendJabber(), MainData, MESSAGE_GetProfile(), MESSAGE_InfoProfile(), and WINDOW_Profile().
Referenced by CONTACT_ShowUserMenu(), and INTERFACE_CreateUserBox().