/home/www/ulysses/webclient/scripts/register/register.js File Reference
Functions
function REGISTER_RegisterData ()
function REGISTER_MakeXMPP (Msg)
function REGISTER_Post ()
function REGISTER_GetError (err)
function REGISTER_DateValidate (User, Mail, Pwd, ConfPW)
function REGISTER_SendData (Msg)
function REGISTER_ReceiveXml ()
function REGISTER_ProcessMessage (XmlDoc)
function REGISTER_SucessMessage ()
function REGISTER_ParseError (code)
function REGISTER_GetLanguage (URL)
function REGISTER_GetHost ()
function REGISTER_Labels ()
function REGISTER_VerticalAlignMiddle ()
Align main div in middle.
function REGISTER_SendDataPHP (User, Mail, Pwd)
function REGISTER_ReceiveXmlPHP ()
function REGISTER_GetDatabaseError (Msg)
Variables
var HttpRequest
var RegisterData
Function Documentation
function REGISTER_DateValidate (User, Mail, Pwd, ConfPW)
Referenced by REGISTER_Post().
function REGISTER_GetDatabaseError (Msg)
Show a alert with error
Returns: none
Author: Fabiano
Deprecated
References UTILS_GetText().
Referenced by REGISTER_ReceiveXmlPHP().
function REGISTER_GetError (err)
References REGISTER_GetLanguage(), UTILS_GetTag(), and UTILS_OpenXMLFile().
Referenced by REGISTER_Post().
function REGISTER_GetHost ()
References UTILS_GetTag(), and UTILS_OpenXMLFile().
Referenced by REGISTER_RegisterData().
function REGISTER_GetLanguage (URL)
Referenced by REGISTER_GetError(), REGISTER_Labels(), REGISTER_ParseError(), and REGISTER_SucessMessage().
function REGISTER_Labels ()
References REGISTER_GetLanguage(), UTILS_GetTag(), and UTILS_OpenXMLFile().
function REGISTER_MakeXMPP (Msg)
References RegisterData.
Referenced by REGISTER_ProcessMessage().
function REGISTER_ParseError (code)
Show a alert box to error in register
Returns: none
Author: Fabiano
References REGISTER_GetLanguage(), UTILS_GetTag(), and UTILS_OpenXMLFile().
Referenced by REGISTER_ProcessMessage().
function REGISTER_Post ()
References REGISTER_DateValidate(), REGISTER_GetError(), REGISTER_RegisterData(), REGISTER_SendData(), and RegisterData.
function REGISTER_ProcessMessage (XmlDoc)
Process the XMPP register response
Returns: none
Author: Fabiano
References REGISTER_MakeXMPP(), REGISTER_ParseError(), REGISTER_SendData(), REGISTER_SucessMessage(), and RegisterData.
Referenced by REGISTER_ReceiveXml().
function REGISTER_ReceiveXml ()
Check and parse the XMPP register response
Returns: none
Author: Fabiano
References HttpRequest, and REGISTER_ProcessMessage().
Referenced by REGISTER_SendData().
function REGISTER_ReceiveXmlPHP ()
Receive response from PHP file
Returns: none
Author: Fabiano
Deprecated
References HttpRequest, and REGISTER_GetDatabaseError().
Referenced by REGISTER_SendDataPHP().
function REGISTER_RegisterData ()
References REGISTER_GetHost().
Referenced by REGISTER_Post().
function REGISTER_SendData (Msg)
References HttpRequest, REGISTER_ReceiveXml(), and RegisterData.
Referenced by REGISTER_Post(), and REGISTER_ProcessMessage().
function REGISTER_SendDataPHP (User, Mail, Pwd)
Send register data to a PHP file (used if jabber don't support user register)
Returns: none
Author: Fabiano
Deprecated
References HttpRequest, and REGISTER_ReceiveXmlPHP().
function REGISTER_SucessMessage ()
Show a alert box to sucess register
Returns: none
Author: Fabiano
References REGISTER_GetLanguage(), UTILS_GetTag(), and UTILS_OpenXMLFile().
Referenced by REGISTER_ProcessMessage().
function REGISTER_VerticalAlignMiddle ()
Align main div in middle.
Author: Rubens
Variable Documentation
var HttpRequest
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. Register window functions
Referenced by REGISTER_ReceiveXml(), REGISTER_ReceiveXmlPHP(), REGISTER_SendData(), and REGISTER_SendDataPHP().
var RegisterData
Referenced by REGISTER_MakeXMPP(), REGISTER_Post(), REGISTER_ProcessMessage(), and REGISTER_SendData().