/home/www/ulysses/webclient/scripts/contact/status.js File Reference
Functions
function CONTACT_ChangeStatus (NewStatus, DontSend)
function CONTACT_SetUserStatus (Username, NewStatus)
Function Documentation
function CONTACT_ChangeStatus (NewStatus, DontSend)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Handle users status Change User Status
References CONNECTION_SendJabber(), MainData, MESSAGE_ChangeStatus(), UTILS_Capitalize(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by GAME_End(), GAME_StartGame(), and INTERFACE_CreateUserBox().
function CONTACT_SetUserStatus (Username, NewStatus)
Change status of 'Username' in structure and interface
References MainData.
Referenced by CONTACT_HandleUserPresence(), and CONTACT_ReceiveUnsubscribed().