/home/www/ulysses/webclient/scripts/interface/top.js File Reference
Functions
function INTERFACE_CreateTop ()
function INTERFACE_ShowRoomMenu (OffsetLeft)
function INTERFACE_ShowGameRoomMenu (OffsetLeft)
function INTERFACE_ShowChallengeMenu (OffsetLeft)
Function Documentation
function INTERFACE_CreateTop ()
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Create element of top of the screen
References INTERFACE_ShowChallengeMenu(), LOGIN_Logout(), MainData, OLDGAME_OpenOldGameWindow(), ROOM_ShowGameRoomList(), ROOM_ShowRoomList(), UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetOffset(), UTILS_GetText(), WINDOW_Alert(), WINDOW_SearchUser(), and WINDOW_UnbanUser().
Referenced by INTERFACE_CreateInterface().
function INTERFACE_ShowChallengeMenu (OffsetLeft)
Show challange menu
Returns: bool
Author: Ulysses
References INTERFACE_HideChallengeList(), MainData, UTILS_AddListener(), UTILS_CreateElement(), and UTILS_RemoveListener().
Referenced by INTERFACE_CreateTop().
function INTERFACE_ShowGameRoomMenu (OffsetLeft)
Show rooms menu
See also: room/room.js: ROOM_HandleGameRoomInfoList to load list itens
Returns: bool
Author: Ulysses
References INTERFACE_HideGameRoomList(), UTILS_AddListener(), UTILS_CreateElement(), and UTILS_RemoveListener().
Referenced by ROOM_ShowGameRoomList().
function INTERFACE_ShowRoomMenu (OffsetLeft)
Show rooms menu
References INTERFACE_HideRoomList(), UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetText(), UTILS_RemoveListener(), and WINDOW_CreateRoom().
Referenced by ROOM_ShowRoomList().